-- Initial schema (no data). Extracted from migrations/dumps/dump.sql - public schema only.
-- Run this first; then 001, 002, 003, 004, 005, 006.

CREATE TABLE IF NOT EXISTS "public"."accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "description" "text",
    "type" "text",
    "currency" "text",
    "balance" double precision
);


ALTER TABLE "public"."accounts" OWNER TO "postgres";


COMMENT ON TABLE "public"."accounts" IS 'Accounts where you have money';



ALTER TABLE "public"."accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."budgets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "category_id" bigint,
    "amount" double precision
);


ALTER TABLE "public"."budgets" OWNER TO "postgres";


COMMENT ON TABLE "public"."budgets" IS 'Budgets for each category ';



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text" NOT NULL,
    "description" "text",
    "is_essential" boolean DEFAULT false
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


COMMENT ON TABLE "public"."categories" IS 'List of expense categories to be used ';



CREATE TABLE IF NOT EXISTS "public"."expenses" (
    "id" bigint NOT NULL,
    "date" "text",
    "category" "text",
    "expense" double precision,
    "description" "text",
    "method" "text",
    "originalAmount" double precision,
    "category_id" bigint,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "account_id" bigint,
    "account_type" "text"
);


ALTER TABLE "public"."expenses" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."budget_by_category_current_month" AS
 WITH "monthlyexpenses" AS (
         SELECT "e_1"."id",
            "e_1"."date",
            "e_1"."category",
            "e_1"."expense",
            "e_1"."description",
            "e_1"."method",
            "e_1"."originalAmount",
            "e_1"."category_id",
            "e_1"."created_at",
            "date_trunc"('MONTH'::"text", "e_1"."created_at") AS "expense_month"
           FROM "public"."expenses" "e_1"
          WHERE (("e_1"."created_at" >= "date_trunc"('MONTH'::"text", (CURRENT_DATE)::timestamp with time zone)) AND ("e_1"."created_at" < ("date_trunc"('MONTH'::"text", (CURRENT_DATE)::timestamp with time zone) + '1 mon'::interval)))
        )
 SELECT "b"."amount",
    "c"."name" AS "category_name",
    "b"."category_id",
    COALESCE("sum"("e"."expense"), (0)::double precision) AS "spent"
   FROM (("public"."budgets" "b"
     JOIN "public"."categories" "c" ON (("b"."category_id" = "c"."id")))
     LEFT JOIN "monthlyexpenses" "e" ON (("b"."category_id" = "e"."category_id")))
  GROUP BY "b"."amount", "c"."name", "b"."category_id"
  ORDER BY "b"."category_id";


ALTER TABLE "public"."budget_by_category_current_month" OWNER TO "postgres";


ALTER TABLE "public"."budgets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."budgets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."config" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "type" "text",
    "sheet" "text",
    "range" "text"
);


ALTER TABLE "public"."config" OWNER TO "postgres";


COMMENT ON TABLE "public"."config" IS 'Configuration objects for each module to be synced';



ALTER TABLE "public"."config" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."config_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."debtors" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "description" "text",
    "first_name" "text",
    "last_name" "text"
);


ALTER TABLE "public"."debtors" OWNER TO "postgres";


COMMENT ON TABLE "public"."debtors" IS 'People of which you borrow and lend money';



CREATE TABLE IF NOT EXISTS "public"."debts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "text",
    "debtor_id" bigint,
    "debtor_name" "text",
    "amount" double precision,
    "original_amount" double precision,
    "currency" "text",
    "outbound" boolean,
    "description" "text"
);


ALTER TABLE "public"."debts" OWNER TO "postgres";


COMMENT ON TABLE "public"."debts" IS 'Borrow and lending transactions';



CREATE OR REPLACE VIEW "public"."debt_by_debtor" AS
 SELECT "d"."id" AS "debtor_id",
    "d"."name" AS "debtor_name",
    "sum"(
        CASE
            WHEN ("debts"."outbound" = true) THEN "debts"."amount"
            ELSE (- "debts"."amount")
        END) AS "net_amount",
    "sum"(
        CASE
            WHEN ("debts"."outbound" = false) THEN "debts"."amount"
            ELSE (0)::double precision
        END) AS "total_amount_lent",
    "sum"(
        CASE
            WHEN ("debts"."outbound" = true) THEN "debts"."amount"
            ELSE (0)::double precision
        END) AS "total_amount_borrowed",
    "count"("debts"."id") AS "transaction_count"
   FROM ("public"."debtors" "d"
     JOIN "public"."debts" ON (("d"."id" = "debts"."debtor_id")))
  GROUP BY "d"."name", "d"."id";


ALTER TABLE "public"."debt_by_debtor" OWNER TO "postgres";


ALTER TABLE "public"."debtors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."debtors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."debts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."debts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."expenses" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."expenses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."incomes" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "date" "text",
    "amount" double precision,
    "description" "text",
    "account_id" bigint,
    "account_name" "text"
);


ALTER TABLE "public"."incomes" OWNER TO "postgres";


COMMENT ON TABLE "public"."incomes" IS 'Ingress transaction to a specific account';



ALTER TABLE "public"."incomes" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."incomes_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."investment_accounts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" "text",
    "description" "text",
    "type" "text",
    "currency" "text",
    "balance" double precision,
    "capital" double precision
);


ALTER TABLE "public"."investment_accounts" OWNER TO "postgres";


COMMENT ON TABLE "public"."investment_accounts" IS 'Accounts that have variable return rates ';



ALTER TABLE "public"."investment_accounts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."investment_accounts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."accounts"
    ADD CONSTRAINT "accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."budgets"
    ADD CONSTRAINT "budgets_category_id_key" UNIQUE ("category_id");



ALTER TABLE ONLY "public"."budgets"
    ADD CONSTRAINT "budgets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."config"
    ADD CONSTRAINT "config_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."config"
    ADD CONSTRAINT "config_type_key" UNIQUE ("type");



ALTER TABLE ONLY "public"."debtors"
    ADD CONSTRAINT "debtors_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."debts"
    ADD CONSTRAINT "debts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."expenses"
    ADD CONSTRAINT "expenses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."incomes"
    ADD CONSTRAINT "incomes_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."investment_accounts"
    ADD CONSTRAINT "investment_accounts_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."investment_accounts"
    ADD CONSTRAINT "investment_accounts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."budgets"
    ADD CONSTRAINT "public_budgets_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id");



ALTER TABLE ONLY "public"."debts"
    ADD CONSTRAINT "public_debts_debtor_id_fkey" FOREIGN KEY ("debtor_id") REFERENCES "public"."debtors"("id");



ALTER TABLE ONLY "public"."expenses"
    ADD CONSTRAINT "public_expenses_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id");



CREATE POLICY "Enable insert for authenticated users only" ON "public"."accounts" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."budgets" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."categories" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."debts" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for authenticated users only" ON "public"."expenses" TO "authenticated";



CREATE POLICY "Enable insert for authenticated users only" ON "public"."incomes" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."config" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable read access for authenticated users" ON "public"."incomes" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "Enable read access for authenticates users" ON "public"."debts" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."accounts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "authenticated select" ON "public"."categories" FOR SELECT TO "authenticated" USING (true);



ALTER TABLE "public"."budgets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."config" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."debtors" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."debts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."expenses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."incomes" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert for auth" ON "public"."accounts" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "insert for auth" ON "public"."debtors" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "insert for auth" ON "public"."investment_accounts" FOR INSERT TO "authenticated" WITH CHECK (true);



ALTER TABLE "public"."investment_accounts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "select for auth" ON "public"."accounts" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "select for auth" ON "public"."debtors" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "select for auth" ON "public"."investment_accounts" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "select for authenticated" ON "public"."budgets" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "select for authenticated" ON "public"."config" FOR SELECT TO "authenticated" USING (true);



CREATE POLICY "update for auth" ON "public"."accounts" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "update for auth" ON "public"."debtors" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "update for auth" ON "public"."investment_accounts" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "update for authenticated" ON "public"."budgets" FOR UPDATE TO "authenticated" USING (true);



CREATE POLICY "update for authenticated" ON "public"."config" FOR UPDATE TO "authenticated" USING (true) WITH CHECK (true);



CREATE POLICY "user auth " ON "public"."expenses" TO "authenticated" USING (true);




GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."accounts" TO "anon";
GRANT ALL ON TABLE "public"."accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."accounts_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."budgets" TO "anon";
GRANT ALL ON TABLE "public"."budgets" TO "authenticated";
GRANT ALL ON TABLE "public"."budgets" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."expenses" TO "anon";
GRANT ALL ON TABLE "public"."expenses" TO "authenticated";
GRANT ALL ON TABLE "public"."expenses" TO "service_role";



GRANT ALL ON TABLE "public"."budget_by_category_current_month" TO "anon";
GRANT ALL ON TABLE "public"."budget_by_category_current_month" TO "authenticated";
GRANT ALL ON TABLE "public"."budget_by_category_current_month" TO "service_role";



GRANT ALL ON SEQUENCE "public"."budgets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."budgets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."budgets_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."config" TO "anon";
GRANT ALL ON TABLE "public"."config" TO "authenticated";
GRANT ALL ON TABLE "public"."config" TO "service_role";



GRANT ALL ON SEQUENCE "public"."config_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."config_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."config_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."debtors" TO "anon";
GRANT ALL ON TABLE "public"."debtors" TO "authenticated";
GRANT ALL ON TABLE "public"."debtors" TO "service_role";



GRANT ALL ON TABLE "public"."debts" TO "anon";
GRANT ALL ON TABLE "public"."debts" TO "authenticated";
GRANT ALL ON TABLE "public"."debts" TO "service_role";



GRANT ALL ON TABLE "public"."debt_by_debtor" TO "anon";
GRANT ALL ON TABLE "public"."debt_by_debtor" TO "authenticated";
GRANT ALL ON TABLE "public"."debt_by_debtor" TO "service_role";



GRANT ALL ON SEQUENCE "public"."debtors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."debtors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."debtors_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."debts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."debts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."debts_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."expenses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."expenses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."expenses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."incomes" TO "anon";
GRANT ALL ON TABLE "public"."incomes" TO "authenticated";
GRANT ALL ON TABLE "public"."incomes" TO "service_role";



GRANT ALL ON SEQUENCE "public"."incomes_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."incomes_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."incomes_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."investment_accounts" TO "anon";
GRANT ALL ON TABLE "public"."investment_accounts" TO "authenticated";
GRANT ALL ON TABLE "public"."investment_accounts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."investment_accounts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."investment_accounts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."investment_accounts_id_seq" TO "service_role";
