-- ============================================
-- PHASE 1: DATABASE SCHEMA UPDATES
-- Foundation for financial tracking enhancements
-- Run in Supabase SQL Editor
-- ============================================

-- 1. Add new columns to investment_accounts
ALTER TABLE investment_accounts 
ADD COLUMN IF NOT EXISTS starting_capital DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS starting_date TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. (Seed data: starting_capital/capital/starting_date per investment_account → seeds/seed_001_phase1_foundation_data.sql)

-- 3. Add starting columns to accounts
ALTER TABLE accounts 
ADD COLUMN IF NOT EXISTS starting_balance DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS starting_date TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 4. (Seed data: starting_balance/starting_date per account → seeds/seed_001_phase1_foundation_data.sql)

-- 5. Create investments table
CREATE TABLE IF NOT EXISTS investments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    date TEXT,
    description TEXT,
    amount DOUBLE PRECISION NOT NULL,
    account_id BIGINT REFERENCES investment_accounts(id),
    account_name TEXT,
    type TEXT NOT NULL CHECK (type IN ('deposit', 'withdrawal'))
);

ALTER TABLE investments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select for auth" ON investments FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert for auth" ON investments FOR INSERT TO authenticated WITH CHECK (true);
GRANT ALL ON TABLE investments TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE investments_id_seq TO anon, authenticated, service_role;

-- 6. Create yearly_goals table
CREATE TABLE IF NOT EXISTS yearly_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    year INTEGER UNIQUE NOT NULL,
    savings_goal DOUBLE PRECISION DEFAULT 0,
    investment_goal DOUBLE PRECISION DEFAULT 0,
    ideal_investment DOUBLE PRECISION DEFAULT 0
);

ALTER TABLE yearly_goals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select for auth" ON yearly_goals FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert for auth" ON yearly_goals FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "update for auth" ON yearly_goals FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
GRANT ALL ON TABLE yearly_goals TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE yearly_goals_id_seq TO anon, authenticated, service_role;

-- (Seed data: yearly_goals rows → seeds/seed_001_phase1_foundation_data.sql and seed_005_baseline_data.sql)

-- 7. Create net_worth_snapshots table
CREATE TABLE IF NOT EXISTS net_worth_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    total_fiat_balance DOUBLE PRECISION DEFAULT 0,
    crypto_balance DOUBLE PRECISION DEFAULT 0,
    crypto_capital DOUBLE PRECISION DEFAULT 0,
    broker_balance DOUBLE PRECISION DEFAULT 0,
    broker_capital DOUBLE PRECISION DEFAULT 0,
    total_investment_balance DOUBLE PRECISION DEFAULT 0,
    total_investment_capital DOUBLE PRECISION DEFAULT 0,
    total_net_worth DOUBLE PRECISION DEFAULT 0,
    total_pnl DOUBLE PRECISION DEFAULT 0,
    fiat_percent DOUBLE PRECISION DEFAULT 0,
    crypto_percent DOUBLE PRECISION DEFAULT 0,
    broker_percent DOUBLE PRECISION DEFAULT 0,
    UNIQUE(year, month)
);

ALTER TABLE net_worth_snapshots ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select for auth" ON net_worth_snapshots FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert for auth" ON net_worth_snapshots FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "update for auth" ON net_worth_snapshots FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
GRANT ALL ON TABLE net_worth_snapshots TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE net_worth_snapshots_id_seq TO anon, authenticated, service_role;

-- 8. Create views
CREATE OR REPLACE VIEW investment_account_summary AS
SELECT 
    id,
    name,
    type,
    currency,
    balance as real_balance,
    capital as total_capital,
    starting_capital,
    balance - capital as pnl,
    CASE WHEN capital > 0 THEN ((balance - capital) / capital) * 100 ELSE 0 END as pnl_percent
FROM investment_accounts;

GRANT ALL ON investment_account_summary TO anon, authenticated, service_role;

CREATE OR REPLACE VIEW monthly_income_summary AS
SELECT 
    EXTRACT(YEAR FROM created_at)::INTEGER as year,
    EXTRACT(MONTH FROM created_at)::INTEGER as month,
    SUM(amount) as total_income
FROM incomes
GROUP BY EXTRACT(YEAR FROM created_at), EXTRACT(MONTH FROM created_at)
ORDER BY year, month;

GRANT ALL ON monthly_income_summary TO anon, authenticated, service_role;

CREATE OR REPLACE VIEW monthly_investment_summary AS
SELECT 
    EXTRACT(YEAR FROM created_at)::INTEGER as year,
    EXTRACT(MONTH FROM created_at)::INTEGER as month,
    account_id,
    account_name,
    SUM(CASE WHEN type = 'deposit' THEN amount ELSE 0 END) as deposits,
    SUM(CASE WHEN type = 'withdrawal' THEN amount ELSE 0 END) as withdrawals,
    SUM(CASE WHEN type = 'deposit' THEN amount ELSE -amount END) as net
FROM investments
GROUP BY EXTRACT(YEAR FROM created_at), EXTRACT(MONTH FROM created_at), account_id, account_name
ORDER BY year, month;

GRANT ALL ON monthly_investment_summary TO anon, authenticated, service_role;

-- 9. (Seed data: config income_monthly sheet/range → seeds/seed_001_phase1_foundation_data.sql)

-- ============================================
-- VERIFY: Run these queries to check
-- ============================================
-- SELECT id, name, capital, starting_capital, balance, starting_date FROM investment_accounts;
-- SELECT id, name, balance, starting_balance, starting_date FROM accounts;
-- SELECT * FROM investments LIMIT 5;
-- SELECT * FROM investment_account_summary;
-- SELECT * FROM yearly_goals;
-- SELECT * FROM net_worth_snapshots;
-- SELECT * FROM config WHERE type = 'income_monthly';
