-- ============================================
-- PHASE 1B: TRANSFERS & DEBT ENHANCEMENTS
-- Run AFTER 001_phase1_foundation.sql
-- ============================================

-- 1. Create transfers table (fiat ↔ fiat)
-- Tracks money moving between accounts, including currency conversion
CREATE TABLE IF NOT EXISTS transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    date TEXT,
    description TEXT,
    source_account_id BIGINT REFERENCES accounts(id),
    source_amount DOUBLE PRECISION NOT NULL,
    dest_account_id BIGINT REFERENCES accounts(id),
    dest_amount DOUBLE PRECISION NOT NULL,
    exchange_rate DOUBLE PRECISION  -- dest_amount / source_amount (for currency conversions)
);

ALTER TABLE transfers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "select for auth" ON transfers FOR SELECT TO authenticated USING (true);
CREATE POLICY "insert for auth" ON transfers FOR INSERT TO authenticated WITH CHECK (true);
GRANT ALL ON TABLE transfers TO anon, authenticated, service_role;
GRANT ALL ON SEQUENCE transfers_id_seq TO anon, authenticated, service_role;

-- 2. Add source_account_id to investments
-- Tracks which fiat account funds come from (deposits) or go to (withdrawals)
ALTER TABLE investments 
ADD COLUMN IF NOT EXISTS source_account_id BIGINT REFERENCES accounts(id);

-- 3. Enhance debts table for expense/income linking
-- account_id: which account was affected
-- expense_id: link to expense that caused this debt (for expense splits/loans)
-- income_id: link to income that settles this debt (for repayments)
-- NOTE: Multiple debts can reference the same expense_id (e.g., dinner split 3 ways)
ALTER TABLE debts 
ADD COLUMN IF NOT EXISTS account_id BIGINT REFERENCES accounts(id),
ADD COLUMN IF NOT EXISTS expense_id BIGINT REFERENCES expenses(id),
ADD COLUMN IF NOT EXISTS income_id BIGINT REFERENCES incomes(id);

-- 4. Create expected balance view
-- Calculates expected balance from all tracked cash movements
-- Debts are EXCLUDED - they're tracking records, not cash flow
-- Formula: starting + income - expenses - inv_deposits + inv_withdrawals - transfers_out + transfers_in
CREATE OR REPLACE VIEW account_expected_balance AS
SELECT 
    a.id,
    a.name,
    a.currency,
    a.starting_balance,
    a.starting_date,
    -- Individual components for debugging
    COALESCE((
        SELECT SUM(amount) FROM incomes 
        WHERE account_id = a.id AND created_at >= a.starting_date
    ), 0) as total_income,
    COALESCE((
        SELECT SUM(expense) FROM expenses 
        WHERE account_id = a.id AND created_at >= a.starting_date
    ), 0) as total_expenses,
    COALESCE((
        SELECT SUM(amount) FROM investments 
        WHERE source_account_id = a.id AND type = 'deposit' AND created_at >= a.starting_date
    ), 0) as total_investment_deposits,
    COALESCE((
        SELECT SUM(amount) FROM investments 
        WHERE source_account_id = a.id AND type = 'withdrawal' AND created_at >= a.starting_date
    ), 0) as total_investment_withdrawals,
    COALESCE((
        SELECT SUM(source_amount) FROM transfers 
        WHERE source_account_id = a.id AND created_at >= a.starting_date
    ), 0) as total_transfers_out,
    COALESCE((
        SELECT SUM(dest_amount) FROM transfers 
        WHERE dest_account_id = a.id AND created_at >= a.starting_date
    ), 0) as total_transfers_in,
    -- Calculated expected balance
    a.starting_balance
        + COALESCE((SELECT SUM(amount) FROM incomes WHERE account_id = a.id AND created_at >= a.starting_date), 0)
        - COALESCE((SELECT SUM(expense) FROM expenses WHERE account_id = a.id AND created_at >= a.starting_date), 0)
        - COALESCE((SELECT SUM(amount) FROM investments WHERE source_account_id = a.id AND type = 'deposit' AND created_at >= a.starting_date), 0)
        + COALESCE((SELECT SUM(amount) FROM investments WHERE source_account_id = a.id AND type = 'withdrawal' AND created_at >= a.starting_date), 0)
        - COALESCE((SELECT SUM(source_amount) FROM transfers WHERE source_account_id = a.id AND created_at >= a.starting_date), 0)
        + COALESCE((SELECT SUM(dest_amount) FROM transfers WHERE dest_account_id = a.id AND created_at >= a.starting_date), 0)
    AS expected_balance,
    -- Real balance from reconciliation
    a.balance as real_balance,
    -- Discrepancy (positive = real > expected, negative = real < expected)
    a.balance - (
        a.starting_balance
        + COALESCE((SELECT SUM(amount) FROM incomes WHERE account_id = a.id AND created_at >= a.starting_date), 0)
        - COALESCE((SELECT SUM(expense) FROM expenses WHERE account_id = a.id AND created_at >= a.starting_date), 0)
        - COALESCE((SELECT SUM(amount) FROM investments WHERE source_account_id = a.id AND type = 'deposit' AND created_at >= a.starting_date), 0)
        + COALESCE((SELECT SUM(amount) FROM investments WHERE source_account_id = a.id AND type = 'withdrawal' AND created_at >= a.starting_date), 0)
        - COALESCE((SELECT SUM(source_amount) FROM transfers WHERE source_account_id = a.id AND created_at >= a.starting_date), 0)
        + COALESCE((SELECT SUM(dest_amount) FROM transfers WHERE dest_account_id = a.id AND created_at >= a.starting_date), 0)
    ) as discrepancy
FROM accounts a;

GRANT ALL ON account_expected_balance TO anon, authenticated, service_role;

-- 5. Update debt_by_debtor view
-- Shows net owed per debtor (positive = they owe you, negative = you owe them)
-- Drop first since column names changed
DROP VIEW IF EXISTS debt_by_debtor;
CREATE OR REPLACE VIEW debt_by_debtor AS
SELECT 
    d.id as debtor_id,
    d.name as debtor_name,
    COALESCE(SUM(CASE WHEN debts.outbound THEN debts.amount ELSE 0 END), 0) as total_lent,
    COALESCE(SUM(CASE WHEN NOT debts.outbound THEN debts.amount ELSE 0 END), 0) as total_received,
    COALESCE(SUM(CASE WHEN debts.outbound THEN debts.amount ELSE -debts.amount END), 0) as net_owed,
    COUNT(debts.id) as transaction_count
FROM debtors d
LEFT JOIN debts ON d.id = debts.debtor_id
GROUP BY d.id, d.name;

GRANT ALL ON debt_by_debtor TO anon, authenticated, service_role;

-- ============================================
-- VERIFY PHASE 1B
-- ============================================
-- SELECT * FROM transfers LIMIT 1;
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'investments' AND column_name = 'source_account_id';
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'debts' AND column_name IN ('account_id', 'expense_id', 'income_id');
-- SELECT * FROM account_expected_balance;
-- SELECT * FROM debt_by_debtor;
